language: python
python:
    - 2.7
    - 3.4
before_install:
    - pip install pep8
install:
    - pip install . --use-mirrors
script:
    - python setup.py nosetests
    - pep8 --ignore=E501 relateiq/
    - pep8 --ignore=E501 tests/

